services:
  postgres:
    extends:
      file: server-config.yml
      service: postgres-base
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - poemsdb-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backup:
    extends:
      file: server-config.yml
      service: backup-base
    volumes:
      - ./backups:/backups
    depends_on:
      - postgres

volumes:
  poemsdb-data: